# FROM alpine:3.8
FROM ubuntu:16.04

# Update build
RUN apt-get update

# Install Python 2, 3, text editor and file move utilities
RUN apt-get install -y python2.7
RUN apt-get install -y python-pip
# RUN apt-get install -y nano
RUN apt-get install -y rsync
RUN pip install azure-storage==0.32.0

# ADD /resources .
COPY copy_to_blob.py copy_to_blob.py
COPY lb_hb.tar.gz lb_hb.tar.gz
COPY radiance-5.1.0-Linux.tar.gz radiance-5.1.0-Linux.tar.gz
COPY RunHoneybeeRadiance.py RunHoneybeeRadiance.py

RUN tar xzf lb_hb.tar.gz
RUN tar xzf radiance-5.1.0-Linux.tar.gz
RUN rsync -av /radiance-5.1.0-Linux/usr/local/radiance/bin/ /usr/local/bin/
RUN rsync -av /radiance-5.1.0-Linux/usr/local/radiance/lib/ /usr/local/lib/ray/

RUN rm ./lb_hb.tar.gz ./radiance-5.1.0-Linux.tar.gz