# Load the recipe.json
# Load the geometry.json
# Generate the Radiance case from the reconstituted recipe
# Run the case using command prompts generated by Honeybee
# Process the results to give actual bona-fide analysis data as JSON outputs for ease of processing later on!